# Generated by Django 5.1.3 on 2024-11-20 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_semester_end_date_alter_semester_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 11, 20)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 11, 20)),
        ),
    ]
